kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: ghproxy
  name: ghproxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ghproxy.volumeSize }}Gi