apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook
  labels:
    app: hook
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hook
  template:
    metadata:
      labels:
        app: hook
    spec:
      serviceAccountName: "hook"
      terminationGracePeriodSeconds: 180
      containers:
      - name: hook
        image: {{ .Values.hook.image }}
        imagePullPolicy: Always
        args:
        - --dry-run={{ .Values.dryRun }}
        - --deck-url=http://deck/
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --github-token-path=/etc/github/token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --kubeconfig=/etc/kubeconfig/config
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: True
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: shared-bins
          mountPath: /shared-bins
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
      initContainers:
      - name: aws-iam-authenticator
        image: {{ .Values.awsIamAuthenticator.image }}
        command:
        - cp
        - /aws-iam-authenticator
        - /shared-bins/aws-iam-authenticator
        volumeMounts:
        - name: shared-bins
          mountPath: /shared-bins
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: github-token
        secret:
          secretName: github-token
      - name: config
        configMap:
          name: config
      - name: plugins
        configMap:
          name: plugins
      - name: job-config
        configMap:
          name: job-config
      - name: shared-bins
        emptyDir: {}
      - name: kubeconfig
        secret:
          defaultMode: 0644
          secretName: kubeconfig
