apiVersion: apps/v1
kind: Deployment
metadata:
  name: prow-controller-manager
  labels:
    app: prow-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow-controller-manager
  template:
    metadata:
      labels:
        app: prow-controller-manager
    spec:
      serviceAccountName: prow-controller-manager
      containers:
      - name: prow-controller-manager
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        args:
        - --dry-run={{ .Values.dryRun }}
        - --deck-url=http://deck/
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --github-token-path=/etc/github/token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --enable-controller=plank
        - --kubeconfig=/etc/kubeconfig/config
        image: {{ .Values.prowControllerManager.image }}
        volumeMounts:
        - name: github-token
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: shared-bins
          mountPath: /shared-bins
      initContainers:
      - name: aws-iam-authenticator
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        image: {{ .Values.awsIamAuthenticator.image }}
        command:
        - cp
        - /aws-iam-authenticator
        - /shared-bins/aws-iam-authenticator
        volumeMounts:
        - name: shared-bins
          mountPath: /shared-bins
      volumes:
      - name: github-token
        secret:
          secretName: github-token
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: shared-bins
        emptyDir: {}
      - name: kubeconfig
        secret:
          defaultMode: 0644
          secretName: kubeconfig
