{{ if .Values.s3Credentials.Secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "{{ .Values.region }}",
      "access_key": "",
      "endpoint": "",
      "insecure": false,
      "s3_force_path_style": false,
      "secret_key": ""
    }
{{ end }}