apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinker
  labels:
    app: sinker
spec:
  selector:
    matchLabels:
      app: sinker
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      serviceAccountName: "sinker"
      containers:
      - name: sinker
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        image: {{ .Values.sinker.image }}
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --kubeconfig=/etc/kubeconfig/config
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: shared-bins
          mountPath: /shared-bins
      initContainers:
      - name: aws-iam-authenticator
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        image: {{ .Values.awsIamAuthenticator.image }}
        command:
        - cp
        - /aws-iam-authenticator
        - /shared-bins/aws-iam-authenticator
        volumeMounts:
        - name: shared-bins
          mountPath: /shared-bins
      volumes:
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: shared-bins
        emptyDir: {}
      - name: kubeconfig
        secret:
          defaultMode: 0644
          secretName: kubeconfig