kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "hook"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "hook"
subjects:
- kind: User
  name: "hook"
  apiGroup: rbac.authorization.k8s.io