kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-controller-manager
subjects:
- kind: User
  name: "prow-controller-manager"
  apiGroup: rbac.authorization.k8s.io