kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - create
      - patch