kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sinker"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "sinker"
subjects:
- kind: User
  name: "sinker"
  apiGroup: rbac.authorization.k8s.io