kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sinker"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - get
      - patch